org: Kingslanding
space: playground
space-developer:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: 
  - pas_kingslanding_playground_space_developer
space-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: 
  - pas_kingslanding_playground_space_manager
space-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
allow-ssh: false
enable-space-quota: false
enable-security-group: false
enable-remove-users: true
isolation_segment: ""
named-security-groups: []
named_quota: ""
